# Generated by Django 5.1.3 on 2024-12-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact_number',
        ),
    ]
