# Generated by Django 5.1.3 on 2024-12-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
