# Generated by Django 5.1.4 on 2025-01-22 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_availability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='shift_type',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('EVE', 'Evening Shift')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('employee', 'available_date', 'shift_type')},
        ),
    ]
