# Generated by Django 5.1.4 on 2025-01-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='core.shift'),
        ),
    ]
