# Generated by Django 5.1.4 on 2025-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_availability_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
